[project]
name = "reader-lm-api"
version = "0.1.0"
description = "trying to apified reader-lm for myself"
requires-python = ">=3.10"
dependencies = ["fastapi", "uvicorn", "requests", "vllm", "pydantic", "triton"]
